services:
  _defaults:
    autowire: true

  ZeebeTransportBundle\Messenger\Transport\ZeebeTransportFactory:
    tags: ['messenger.transport_factory']

  ZeebeTransportBundle\Command\WorkflowDeployCommand:
    tags: ['console.command']


